name: Build and Deploy Jekyll site
on:
  push:
    branches: [ main ]

permissions:
  contents: write          # allow deployment

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2       # match local
      - run: gem install bundler
      - run: bundle install --jobs 4 --retry 3
      - run: bundle exec jekyll build -d _site
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
